  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: promethus-ingress
    namespace: monitoring
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
  spec:
    tls:
    - hosts:
      - promethus.wandexdev.me
      secretName: prometheus-tls
    rules:
       -  host: promethus.wandexdev.me
          http:
            paths:
            - backend:
                service:
                  name: prometheus
                  port:
                    number: 80
              path: /
              pathType: Prefix