  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: webapp-ingress
    namespace: wandek8s-nodejs
    #annotations:
    #  nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
    ingressClassName: nginx
    rules:
       -  host: webapp.wandexdev.me
          http:
            paths:
            - backend:
                service:
                  name: wandek8s-nodejs
                  port:
                    number: 3000
              path: /
              pathType: Prefix